### ISSUE TITLE
How to install this extension via composer?

### ISSUE THREAD

**Issue by arsnic** [tom--/dynamic-ar#12]
Try this command : composer require tom--/yii2-dynamic-ar .
 But  composer wrote error below:  [InvalidArgumentException]
  Could not find package tom--/yii2-dynamic-ar at any version for your minimu
  m-stability (stable). Check the package spelling or your minimum-stability
Whats wrong? Help me please.

**Comment by tom--** [comment]
The package name is [spinitron/yii2-dynamic-ar](https://github.com/tom--/yii2-dynamic-ar/blob/0.3.0/composer.json#L2). The namespace is `spinitron\dynamicAr`.

Btw: unless you are contributing, use the latest tag. At present it is 0.3.0.

**Comment by cebe** [comment]
the package name is [spinitron/yii2-dynamic-ar](https://github.com/tom--/yii2-dynamic-ar/blob/master/composer.json#L2).
