### ISSUE TITLE
PHP identifier restriction on attribute name is spurious

### ISSUE THREAD

**Issue by tom--** [tom--/dynamic-ar#6]
The restriction on attribute names that they should be (start with) a string that would be a valid PHP identifier, is spurious. It's not the way PHP behaves. Get rid of it.

```
$n = '123';
$$n = 'xyz';
var_dump($$n); 
>>> string(3) "xyz"
$o = new StdClass;
$o->$n = 'abd';
var_dump($o);
    >>> class stdClass#1 (1) {
      public $123 =>
      string(3) "abd"
    }
```

**Comment by djagya** [comment]
@tom-- should i handle that? Or you'll do that?

**Comment by tom--** [comment]
i have fixed it. i made the issue so we have a history of why this changed
